Repository jenkinsci/login-theme-plugin, pull requests merged in 2019-11, with the labels that each got.

#4 Move Documentation from Wiki to GitHub and update Security Notice for Dangerous Permissions
  README.md
  pom.xml
Labels: documentation, hacktoberfest

#3 Added Jenkins Configuration-as-Code support
  pom.xml
  src/main/java/io/jenkins/plugins/logintheme/LoginTheme.java
Labels: enhancement

#5 Add a Release Drafter configuration to the plugin
  .github/release-drafter.yml
Labels: chore

#6 README: Fix the badge link
  README.md
Labels: skip-changelog

#7 Change the target Jenkins baseline from 2.128 to the 2.138.3 LTS
  pom.xml
Labels: chore
