Repository jenkinsci/login-theme-plugin, pull requests merged in 2024-02, with the labels that each got.

#71 Update docs for new features
  README.md
  docs/login_result.png
  docs/login_result_page.jpeg
  docs/system_config.png
  docs/system_config_page.jpeg
Labels: documentation

#74 Add test coverage for functions in LoginTheme
  pom.xml
  src/test/java/io/jenkins/plugins/logintheme/LoginThemeTest.java
Labels: tests

#75 Enable spotless formatting
  .git-blame-ignore-revs
  pom.xml
  src/main/java/io/jenkins/plugins/logintheme/LoginTheme.java
  src/test/java/io/jenkins/plugins/logintheme/ConfigurationAsCodeTest.java
  src/test/java/io/jenkins/plugins/logintheme/LoginThemeTest.java
Labels: chore, skip-changelog

#76 Update .git-blame-ignore-revs with spotless formatting
  .git-blame-ignore-revs
Labels: chore, skip-changelog
